#!/bin/sh
# Sign and publish a release. The release workflow builds each tag into a
# DRAFT; nothing is installable until this signs it, with a key that never
# leaves the maintainer's machine:
#
#   scripts/sign-release.sh v1.2.3 [path/to/private/key]
#
# It checks the draft first — every archive, images.txt and checksums.txt
# were built by this repo's release workflow (build attestation), both GHCR
# images carry the same attestation, and the files match checksums.txt — then
# signs checksums.txt, verifies the signature against the key committed in
# scripts/release_key.pub, uploads it and publishes the release.
# Needs: gh (logged in), ssh-keygen (OpenSSH 8.1+), sha256sum or shasum.
set -eu

REPO="cintelis/bugxhunter-runner"
NS="bugxhunter-release"
tag="${1:?usage: scripts/sign-release.sh vX.Y.Z [private key]}"
key="${2:-$HOME/.ssh/cintelis-release}"
root=$(cd "$(dirname "$0")/.." && pwd)
pub="$root/scripts/release_key.pub"

[ -f "$key" ] || { echo "no private key at $key" >&2; exit 1; }
# the release-table PR at the end is pushed with gh's active account: check
# it can write here before anything is signed or published
who=$(gh api user --jq .login)
if [ "$(gh api "repos/$REPO" --jq .permissions.push)" != "true" ]; then
  echo "gh is logged in as $who, which can't push to $REPO." >&2
  echo "Switch to an account that can: gh auth switch --user <account>" >&2
  exit 1
fi
if [ "$(gh release view "$tag" -R "$REPO" --json isDraft --jq .isDraft)" != "true" ]; then
  echo "$tag is not a draft release (already published, or not built yet)" >&2
  exit 1
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
gh release download "$tag" -R "$REPO" -D "$tmp"

echo "checking build provenance of the archives ..."
for f in "$tmp"/*.tar.gz "$tmp/images.txt" "$tmp/checksums.txt"; do
  gh attestation verify "$f" -R "$REPO" >/dev/null
done

echo "checking build provenance of the images ..."
while IFS= read -r image; do
  [ -n "$image" ] || continue
  gh attestation verify "oci://$image" -R "$REPO" >/dev/null
done < "$tmp/images.txt"

echo "checking checksums ..."
if command -v sha256sum >/dev/null 2>&1; then
  (cd "$tmp" && sha256sum -c --quiet checksums.txt)
else
  (cd "$tmp" && shasum -a 256 -c --quiet checksums.txt)
fi

echo "signing checksums.txt ..."
rm -f "$tmp/checksums.txt.sig"
ssh-keygen -Y sign -f "$key" -n "$NS" "$tmp/checksums.txt"

# the signature must verify with the committed public key
printf '%s namespaces="%s" %s\n' "$NS" "$NS" "$(cut -d' ' -f1,2 "$pub")" > "$tmp/allowed_signers"
ssh-keygen -Y verify -f "$tmp/allowed_signers" -I "$NS" -n "$NS" \
  -s "$tmp/checksums.txt.sig" < "$tmp/checksums.txt"

# --clobber: a rerun after a failed publish replaces the signature it uploaded
# (the release is still a draft, so it can change; once published it can't)
gh release upload "$tag" "$tmp/checksums.txt.sig" -R "$REPO" --clobber
gh release edit "$tag" -R "$REPO" --draft=false --latest
echo "published $tag"

# Record it in the README's release table: a PR that merges itself once CI
# passes. Skipped (with a note) if the checkout has uncommitted work.
if [ -n "$(git -C "$root" status --porcelain)" ]; then
  echo "note: uncommitted changes here, so the release table wasn't updated —" >&2
  echo "      run scripts/release-table.sh on a clean branch and open a PR" >&2
  exit 0
fi
back=$(git -C "$root" branch --show-current)
# Whatever happens below (a failed PR call, Ctrl-C), leave the checkout where
# it was: later commits must not land on the table branch by accident.
trap 'git -C "$root" switch -q "$back" 2>/dev/null || true' EXIT
branch="docs/release-table-$tag"
git -C "$root" fetch -q origin master
git -C "$root" switch -q -c "$branch" origin/master
"$root/scripts/release-table.sh"
git -C "$root" commit -q -am "docs: add $tag to the release table"
git -C "$root" push -q -u origin "$branch"
gh pr create -R "$REPO" --base master --head "$branch" \
  --title "docs: add $tag to the release table" \
  --body "Regenerated by scripts/release-table.sh after publishing $tag. Every row's signature was verified against the release key while generating it."
gh pr merge "$branch" -R "$REPO" --auto --squash --delete-branch
echo "release table PR opened; it merges once CI passes"
